---
- name: Install Cursor extensions
  ansible.builtin.command:
    cmd: "{{ cursor_cli_path }} --install-extension {{ item.id | default(item.name) }}"
  loop: "{{ cursor_extensions }}"
  register: cursor_result
  changed_when: "'already installed' not in cursor_result.stdout"
  when: (item.id | default(item.name)) not in cursor_extensions_exclude
  tags: cursor
