---
- name: Ping Test Playbook
  hosts: mymac
  # connection: local
  gather_facts: true    
  roles:
    - role: homebrew
      tags: ['homebrew']
    - role: appstore
      tags: ['appstore']
    - role: rosetta
      when: ansible_machine == 'arm64'
      tags: ['rosetta']
    - role: zsh
      tags: ['zsh']
    - role: mise
      tags: ['mise']
    - role: ghorg
      tags: ['ghorg']
    - role: gita
      tags: ['gita']
