---
- name: Ping Test Playbook
  hosts: mymac
  connection: local
  gather_facts: true
  roles:
    - role: homebrew
      tags: ['homebrew']
    - role: appstore
      tags: ['appstore']
    - role: rosetta
      when: ansible_machine == 'arm64'
      tags: ['rosetta']
    - role: vim
      tags: ['vim']
    - role: iterm2
      tags: ['iterm2']
    - role: cursor
      tags: ['cursor']
    - role: mise
      tags: ['mise']
    - role: gita
      tags: ['gita']
    - role: copier
      tags: ['copier']
    - role: uv
      tags: ['uv']
    - role: zsh
      tags: ['zsh']
    - role: macos_settings
      tags: ['macos_settings']
    - role: git
      tags: ['git']
    - role: rancher-desktop
      tags: ['rancher-desktop']
