---
- name: Bootstrap workstation
  hosts: all
  connection: local
  gather_facts: true
  roles:
    - role: base-tools
      tags: ["base-tools"]
    - role: appstore
      tags: ["appstore"]
      when: ansible_facts.os_family == 'Darwin'
    - role: rosetta
      when: ansible_facts.os_family == 'Darwin' and ansible_facts.machine == 'arm64'
      tags: ["rosetta"]
    - role: vim
      tags: ["vim"]
    - role: iterm2
      tags: ["iterm2"]
      when: ansible_facts.os_family == 'Darwin' and iterm2_enabled | bool
    - role: warp
      tags: ["warp"]
      when: warp_enabled | bool
    - role: cursor
      tags: ["cursor"]
    - role: claude-code
      tags: ["claude-code"]
    - role: mise
      tags: ["mise"]
    - role: gita
      tags: ["gita"]
    - role: copier
      tags: ["copier"]
    - role: uv
      tags: ["uv"]
    - role: zsh
      tags: ["zsh"]
    - role: macos_settings
      tags: ["macos_settings"]
      when: ansible_facts.os_family == 'Darwin'
    - role: git
      tags: ["git"]
    - role: docker
      tags: ["docker"]
    - role: gpg
      tags: ["gpg"]
