---
version: "3"

tasks:
  default:
    desc: Display helper
    cmds:
      - cmd: task --list-all
    silent: true

  init:
    desc: Init stack
    cmds:
      - mise install
      - pre-commit install
      - uv sync --frozen
      - uv run ansible-galaxy install -r requirements.yml
      - cmd: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        platforms: [darwin]
    run: once

  pre-commit:
    desc: Run pre-commit on all files
    cmds:
      - echo "Running pre-commit hooks..."
      - uv run pre-commit run --all-files

  check:
    desc: Run playbook in check mode
    cmds:
      - echo "Running playbook in check mode..."
      - uv run ansible-playbook main.yml --check --diff --ask-become-pass {{.CLI_ARGS}}

  run:
    desc: Run full playbook
    cmds:
      - uv run ansible-playbook main.yml --ask-become-pass {{.CLI_ARGS}}

  run:*:
    desc: Run playbook by tag
    vars:
      TAG: "{{index .MATCH 0}}"
    cmds:
      - uv run ansible-playbook main.yml --tags {{.TAG}} --ask-become-pass {{.CLI_ARGS}}

  lint:
    desc: Run all linters
    deps:
      - ansiblelint
      - yamllint
      - ansiblesyntaxecheck
    cmds:
      - echo "All linting passed!"

  ansiblelint:
    desc: Launch ansible lint
    aliases:
      - alint
    cmds:
      - uv run ansible-lint -v

  yamllint:
    desc: Run yamllint
    aliases:
      - ylint
    cmds:
      - uv run yamllint -c .yamllint --no-warnings .

  ansiblesyntaxecheck:
    desc: Launch ansible syntax check
    aliases:
      - ascheck
    cmds:
      - uv run ansible-playbook main.yml --syntax-check --ask-become-pass

  full-test:
    desc: Run Molecule test on all roles
    vars:
      ROLES_LIST:
        sh: "ls -d roles/*/ | xargs -n1 basename"
    cmds:
      - for: { var: ROLES_LIST }
        task: test
        vars:
          ROLE: "{{.ITEM}}"

  test:
    internal: true
    dir: roles/{{.ROLE}}
    cmds:
      - echo "Launching test molecule for {{.ROLE}}"
      - uv run molecule test {{.CLI_ARGS}}
    silent: true

  test:*:
    desc: Run Molecule tests for specific role
    preconditions:
      - sh: test -d "molecule"
        msg: "Role {{.ROLE}} does not have Molecule tests"
    dir: roles/{{.ROLE}}
    vars:
      ROLE: "{{index .MATCH 0}}"
    cmds:
      - uv run molecule test {{.CLI_ARGS}}

  converge:*:
    desc: Run Molecule converge for specific role
    preconditions:
      - sh: test -d "molecule"
        msg: "Role {{.ROLE}} does not have Molecule tests"
    dir: roles/{{.ROLE}}
    vars:
      ROLE: "{{index .MATCH 0}}"
    cmds:
      - uv run molecule converge {{.CLI_ARGS}}

  verify:*:
    desc: Run Molecule verify for specific role
    preconditions:
      - sh: test -d "molecule"
        msg: "Role {{.ROLE}} does not have Molecule tests"
    dir: roles/{{.ROLE}}
    vars:
      ROLE: "{{index .MATCH 0}}"
    cmds:
      - uv run molecule verify {{.CLI_ARGS}}

  destroy:*:
    desc: Destroy Molecule instances for specific role
    preconditions:
      - sh: test -d "molecule"
        msg: "Role {{.ROLE}} does not have Molecule tests"
    dir: roles/{{.ROLE}}
    vars:
      ROLE: "{{index .MATCH 0}}"
    cmds:
      - uv run molecule destroy {{.CLI_ARGS}}

  login:*:*:
    desc: Login to Molecule test container
    preconditions:
      - sh: test -d "molecule"
        msg: "Role {{.ROLE}} does not have Molecule tests"
    dir: roles/{{.ROLE}}
    vars:
      ROLE: "{{index .MATCH 0}}"
      HOST: "{{index .MATCH 1}}"
    cmds:
      - uv run molecule list -f simple
      - uv run molecule login --host {{.HOST}}

  list-tags:
    desc: List all available tags
    cmds:
      - uv run ansible-playbook main.yml --list-tags | grep "TASK TAGS:" | sed 's/.*\[//;s/\].*//' | tr ',' '\n' | sed 's/^ *//;s/ *$//' | grep .

  update-galaxy:
    desc: Update Ansible Galaxy roles
    cmds:
      - echo "Updating Ansible Galaxy roles..."
      - uv run ansible-galaxy install -r requirements.yml --force
    silent: true

  version:
    desc: Show versions of installed tools
    cmds:
      - cat .mise.toml |grep -vE "\[tools\]"
      - uv pip list
    silent: true
