---
version: '3'

tasks:
  default:
    cmds:
      - task: init

  init:
    desc: Init stack
    cmds:
      - cmd: mise install
      - cmd: pre-commit install
      - cmd: uv sync --frozen
      - cmd: uv run ansible-galaxy install -r requirements.yml
      - cmd: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

          # Setup Homebrew environment
          if [[ -x /opt/homebrew/bin/brew ]]; then
              eval "$(/opt/homebrew/bin/brew shellenv)"
          elif [[ -x /usr/local/bin/brew ]]; then
              eval "$(/usr/local/bin/brew shellenv)"
          fi
        platforms: [darwin]

  pre-commit:
    desc: Run pre-commit on all files
    cmds:
      - echo "Running pre-commit hooks..."
      - uv run pre-commit run --all-files

  check:
    desc: Run playbook in check mode
    cmds:
      - echo "Running playbook in check mode..."
      - uv run ansible-playbook main.yml --check --diff --ask-become-pass

  run:
    desc: Run full playbook
    cmds:
      - uv run ansible-playbook main.yml --ask-become-pass

  # run-tag:
  #   desc: Run specific role by tag
  #   requires:
  #     vars:
  #       - TAG
  #   cmds:
  #     - echo "Running role: {{.TAG}}"
  #     - ansible-playbook main.yml --tags {{.TAG}}

  lint:
    desc: Run all linters
    deps:
      - ansiblelint
      - yamllint
      - ansiblesyntaxecheck
    cmds:
      - echo "All linting passed!"

  ansiblelint:
    cmds:
      - uv run ansible-lint -v

  yamllint:
    cmds:
      - uv run yamllint -c .yamllint --no-warnings .

  ansiblesyntaxecheck:
    cmds:
      - uv run ansible-playbook main.yml --syntax-check --ask-become-pass

        #  molecule-test:
        #    desc: Run Molecule tests for all roles
        #    cmds:
        #      - echo "Running Molecule tests for all roles..."
        #      - |
        #        for role in roles/*/molecule; do
        #          if [ -d "$role" ]; then
        #            role_name=$(echo $role | cut -d'/' -f2)
        #            echo "Testing role: $role_name"
        #            cd roles/$role_name && molecule test && cd ../..
        #          fi
        #        done
        #      - echo "All Molecule tests passed!"

  test:
    desc: Run Molecule tests for specific role
    preconditions:
      - sh: test -d "molecule"
        msg: "Role {{.CLI_ARGS}} does not have Molecule tests"
    dir: roles/{{.CLI_ARGS}}
    cmds:
      - uv run molecule test

  converge:
    desc: Run Molecule converge for specific role
    preconditions:
      - sh: test -d "molecule"
        msg: "Role {{.CLI_ARGS}} does not have Molecule tests"
    dir: roles/{{.CLI_ARGS}}
    cmds:
      - uv run molecule converge

  verify:
    desc: Run Molecule verify for specific role
    preconditions:
      - sh: test -d "molecule"
        msg: "Role {{.CLI_ARGS}} does not have Molecule tests"
    dir: roles/{{.CLI_ARGS}}
    cmds:
      - uv run molecule verify

  login:
    desc: Login to Molecule test container
    preconditions:
      - sh: test -d "molecule"
        msg: "Role {{.CLI_ARGS}} does not have Molecule tests"
    dir: roles/{{.CLI_ARGS}}
    cmds:
      - uv run molecule login

  destroy:
    desc: Destroy Molecule test container
    preconditions:
      - sh: test -d "molecule"
        msg: "Role {{.CLI_ARGS}} does not have Molecule tests"
    dir: roles/{{.CLI_ARGS}}
    cmds:
      - uv run molecule destroy

  # fulltest:
  #   desc: Run all Molecule tests
  #   cmds:
  #     - uv run molecule test

  # list-tags:
  #   desc: List all available tags
  #   cmds:
  #     - echo "Available tags:"
  #     - grep -h "tags:" main.yml | grep -v "#" | sed 's/.*tags://' | tr -d '[]' | tr ',' '\n' | sed 's/^[ \t]*//' | sort -u


  # update-galaxy:
  #   desc: Update Ansible Galaxy roles
  #   cmds:
  #     - echo "Updating Ansible Galaxy roles..."
  #     - ansible-galaxy install -r requirements.yml --force

  version:
    desc: Show versions of installed tools
    cmds:
      - cat .mise.toml |grep -vE "\[tools\]"
      - uv pip list
    silent: true
