---
name: Docker public image cache
description: Pull and cache a public Docker image for reuse
inputs:
  image_name_tag:
    description: Docker image name and tag to pull and cache
    required: true
runs:
  using: "composite"
  steps:
    - name: Restore image cache
      id: restore_cache
      uses: actions/cache@v4
      with:
        path: 'ci/cache/docker'
        key: 'cache-docker-${{ inputs.image_name_tag }}'

    - name: Update image cache on cache miss
      if: steps.restore_cache.outputs.cache-hit != 'true'
      shell: bash
      run: >
        docker pull '${{ inputs.image_name_tag }}'
        && mkdir -p $(dirname './ci/cache/docker/${{ inputs.image_name_tag }}.tar')
        && docker image save '${{ inputs.image_name_tag }}' --output './ci/cache/docker/${{ inputs.image_name_tag }}.tar'

    - name: Use image cache on cache hit
      if: steps.restore_cache.outputs.cache-hit == 'true'
      shell: bash
      run: >
        docker image load --input './ci/cache/docker/${{ inputs.image_name_tag }}.tar'